package org.texttechnologylab.duui.dua.service;

public enum DUAServiceDataClass {
    CANONICAL_CAS,
    CANONICAL_CORPUS_REGISTRY,
    CANONICAL_PAYLOAD,
    TYPE_SYSTEM,
    REVISION_LOG,
    TRANSPORT_PACKAGE,
    PIPELINE_RUN_STATE,
    PROJECTION_EVENT,
    DERIVED_INDEX,
    DERIVED_ANALYTIC,
    DERIVED_GRAPH,
    DERIVED_VECTOR,
    UI_VIEW_MODEL,
    ACCESS_POLICY,
    TELEMETRY
}
