package org.texttechnologylab.duui.dua.backend;

public enum DUAStoreCapability {
    CAS_SLOT_VALUES,
    FS_COLLECTION_VALUES,
    FS_ID_ALLOCATION,
    ANNOTATION_SPAN_LOOKUP,
    RANGE_JOIN,
    COVERED_TEXT_LOOKUP,
    SUBSTRING_LOOKUP,
    TYPE_HIERARCHY,
    FEATURE_REFERENCE_TRAVERSAL,
    ARCHIVE_BYTES
}
