package org.texttechnologylab.duui.exception;

public enum FailureCategory {
    VALIDATION,
    TRANSIENT_INFRASTRUCTURE,
    PERSISTENT_INFRASTRUCTURE,
    PARSE,
    SEMANTIC_DATA,
    CONFLICT,
    CONCURRENCY,
    RESOURCE_EXHAUSTION,
    PROGRAMMING_BUG,
    OPTIONAL_FEATURE,
    CONSISTENCY,
    CANCELLATION,
    TIMEOUT
}
